### PR TITLE
Begin adding eslint & corresponding configuration

### PR DESCRIPTION
**Pull request by kadamwhite**
### Description of the problem this pull request fixes

This PR adds [eslint](http://eslint.org/) to help us define, standardize & enforce code style within Lyra.
### Changes proposed in this pull request:
- Add the ESLint tool to the project
- Define an `npm run lint` alias
- Begin specifying eslint configuration options
### Further comments:

@deathbearbrown This PR should be considered a WIP, as the rules specified need to be adjusted (it's complaining about JSX syntax, _e.g._) and there are some rules that may conflict with the established style.

I am assuming that this PR will be reviewable/mergeable when the list of errors `npm run lint` produces matches our expectations as a team; ESLint conformance would then be a separate PR. Sue, if you want to run with code changes to get us to this defined reviewable state be my guest; otherwise I'll tackle that first thing on Monday.

Open Qs:
- Do we want to make an intermediate directory for tooling-related things, rather than having `eslint/` sitting in the repo root?

LYRA-261

### CODE REVIEW

**Comment by deathbearbrown** [comment]
All projects I've worked on just had an eslint folder at root and that's fine. 
Also if we need more rules or less later we can always open PRs. This doesn't have to be the end of the linting discussion. 
:dancers:

**Comment by deathbearbrown** [comment]
One error is that eslint@^2.0.0-rc.0 needs to be added to the package.  I don't have that globally installed.

**Comment by kadamwhite** [comment]
@deathbearbrown would it be sufficient to upgrade the package dep to `eslint@^2.0.0-rc.0` ? `npm run lint` should obviate the need to have it globally installed, i try to avoid `-g`.

**Comment by kadamwhite** [comment]
:+1: to Sue's changes; we both worked on this so I'm not sure who should merge it :)

**Comment by kadamwhite** [comment]
The plan post-stand: Sue will push her lint error fix commits, I will pull down, install & test, then I will merge if it checks out

**Comment by deathbearbrown** [comment]
I'm gonna cry if I have to keep fixing linting errors today. I'm gonna take a break and work on tests. 

Note: I removed some of our rules because they were too opinionated.  e.g- There were cases where combining all the vars actually made the code less readable.

**Comment by kadamwhite** [comment]
Awesome, @deathbearbrown. Pulling down and testing

**Comment by kadamwhite** [comment]
A fresh `npm install` and `npm run lint` yields 247 errors, as promised. :+1:, mergin'!

**Pull request merged**
