### PR TITLE
Export as png, svg, json, html

### PR DESCRIPTION
**Pull request by arvind**
**Description of the problem this pull request fixes**

Adds functionality to export the current visualization in PNG, SVG, JSON, and HTML formats. This branch was cut from as/ux-polish (#337). See a [branch specific diff](https://github.com/vega/lyra/compare/as/ux-polish...as/export). 

I've also moved the "Clear All" buttom from the toolbar to the top of the "Groups" sidebar. My hunch is that this should just clear out the visual elements, but keep data pipelines around, rather than starting a user from a total blank clean slate (which can be accomplished via a page page).

export

**This PR includes:**
- [ ] Tests
- [x] functional comments
- [x] high level description of any new components

### CODE REVIEW

**Comment by deathbearbrown** [comment]
@arvind needs a rebase :3

**Comment by deathbearbrown** [comment]
+1 functional.  
One optional nitpick might be to grey out export until something is on the scene. 
But exporting a json object with just the skeleton of the vega object is kind of useful.

**Comment by arvind** [comment]
Ok, rebased. I recommend merging #337 first, just to make sure I rebased this one correctly as well... Phew!

**Comment by deathbearbrown** [comment]
+1 waiting for travis. I AM SO EXCITED

**Pull request merged**
